name: d12-xmobar
version: '0.1.0.0'
author: Boris Buliga
maintainer: Boris Buliga
github: d12frosted/environment

default-extensions: []

ghc-options: -Wall -Werror

executables:
  d12-xmobar:
    main: xmobar.hs
    dependencies:
      - base
      - data-default
      - xmobar
      - d12-hs-path
      - path
