image: d12frosted/environment:archlinux

stages:
  - build

build:
  stage: build
  script:
    - sudo pacman -Syu --noconfirm --needed base-devel git pacman-contrib
    - ./eru.sh
  only:
    - master
