image: d12frosted/environment:archlinux

stages:
  - build

.build_template: &build_definition
  stage: build
  cache:
    paths:
      - /home/d12frosted/.config/xmonad/.stack-work
      - /home/d12frosted/.config/xmonad/.stack-work/
      - /home/d12frosted/.config/xmonad/.stack
  before_script:
    - sudo pacman -Syu --noconfirm --needed base-devel git pacman-contrib

build:
  <<: *build_definition
  script:
    - ./eru.sh
