image: d12frosted/environment:archlinux

stages:
  - build

cache:
  paths:
    - xmonad/.stack-work

.build_template: &build_definition
  stage: build
  before_script:
    - pwd
    - sudo pacman -Syu --noconfirm --needed base-devel git pacman-contrib

build:
  <<: *build_definition
  script:
    - ./eru.sh
