image: d12frosted/environment:archlinux

stages:
  - build

build:
  stage: build
  cache:
    paths:
      - xmobar/.stack-work
      - xmonad/.stack-work
      - taffybar/.stack-work
  script:
    - sudo pacman -Syu --noconfirm --needed base-devel git pacman-contrib
    - ./eru.sh
  only:
    - master
