image: d12frosted/environment:archlinux

stages:
  - build

build:
  stage: build
  cache:
    paths:
      - .stack-work
  script:
    - export STACK_WORK=.stack-work
    - sudo pacman -Syu --noconfirm --needed base-devel git pacman-contrib
    - ./eru.sh
