image: d12frosted/environment:archlinux

stages:
  - build

build:
  stage: build
  cache:
    paths:
      - xmonad/.stack-work
  before_script:
    - export XDG_CONFIG_HOME=$(pwd)
    - echo "XDG_CONFIG_HOME = $XDG_CONFIG_HOME"
    - sudo pacman -Syu --noconfirm --needed base-devel git pacman-contrib
  script:
    - ./eru.sh
