name:                melkor
version:             0.1.0.0
git:                 "https://gitlab.com/d12frosted/environment"
license:             MIT
author:              "Boris Buliga"
maintainer:          "boris@d12frosted.io"
copyright:           "2019-2020 Boris Buliga"

description:         Please see the README on GitLab at <https://gitlab.com/d12frosted/environment>

dependencies:
- base-noprelude >= 4.7 && < 5
- directory
- env-extra
- mtl
- path
- path-extra
- relude
- rio

default-extensions:
  - DeriveFunctor
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - OverloadedStrings

library:
  source-dirs: src

executables:
  melkor:
    main:                Melkor.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-IO
    dependencies:
    - melkor
