name:                melkor
version:             0.1.0.0
git:                 "https://gitlab.com/d12frosted/environment"
license:             MIT
author:              "Boris Buliga"
maintainer:          "boris@d12frosted.io"
copyright:           "2019-2020 Boris Buliga"

description:         Please see the README on GitLab at <https://gitlab.com/d12frosted/environment>

dependencies:
- base >= 4.7 && < 5
- bytestring
- comonad
- containers
- directory
- env-extra
- mtl
- ordered-containers
- path
- path-extra
- rio
- text
- unordered-containers
- hashable

ghc-options:
  - -O2

library:
  source-dirs: src

executables:
  melkor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-IO
    dependencies:
    - melkor

tests:
  melkor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - melkor
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-quickcheck-laws
