name: d12-xmonad
version: '0.1.0.0'
author: Boris Buliga
maintainer: Boris Buliga
github: d12frosted/environment

default-extensions:
  - OverloadedStrings

ghc-options: -Wall -Werror -threaded -rtsopts -with-rtsopts=-N

executables:
  d12-xmonad:
    main: xmonad.hs
    dependencies:
      - X11
      - base
      - data-default
      - process
      - xmonad
      - xmonad-contrib
      - xmonad-extras
