name: d12x
version: '0.1.0.0'
author: Boris Buliga
maintainer: Boris Buliga
github: d12frosted/environment

default-extensions:
  - OverloadedStrings

ghc-options: -Wall -Werror

library:
  source-dirs: lib
  dependencies:
    - base
    - xmonad-contrib

executables:
  d12-xmonad:
    source-dirs: xmonad
    main: Main.hs
    dependencies:
      - X11
      - base
      - d12x
      - data-default
      - xmonad
      - xmonad-contrib
      - xmonad-extras
  d12-xmobar:
    source-dirs: xmobar
    main: Main.hs
    dependencies:
      - base
      - path-extra
      - d12x
      - data-default
      - mtl
      - path
      - process
      - xmobar
