resolver: lts-14.19

packages:
- '.'

extra-deps:
  - xmobar-0.31
  - iwlib-0.1.0
  - git: https://github.com/d12frosted/path-extra
    commit: 8457c546d02c97d06710320de4e834fb0fd46637
  - git: https://github.com/d12frosted/env-extra
    commit: ca7aebf497d92a58c1bd44e1f7f084e2e56efa34

flags:
  xmobar:
    all_extensions: true
