resolver: lts-13.18

packages:
- '.'
- location:
    git: https://gitlab.com/d12frosted/d12-hs-path
    commit: caeca85f001dcc4b1cf1d93d6ef259dceb85b1a7
  extra-dep: true
- location:
    git: https://gitlab.com/d12frosted/d12-hs-env
    commit: b306c70b4a50e2ae2ffc1fe3a84209e00af51ead
  extra-dep: true

extra-deps: []
