resolver: lts-13.18

packages:
- .
- location:
    git: https://github.com/taffybar/taffybar
    commit: d4f983fe3f6ab1278aed1cc884b5afbcf1f4415d
  extra-dep: true

extra-deps:
- ConfigFile-1.1.4
- broadcast-chan-0.2.0.2
- dbus-hslogger-0.1.0.1
- gi-cairo-connector-0.0.1
- gi-cairo-render-0.0.1
- gi-dbusmenu-0.4.1
- gi-dbusmenugtk3-0.4.2
- gi-gdkx11-3.0.4
- gi-xlib-2.0.2
- gtk-sni-tray-0.1.6.0
- gtk-strut-0.1.3.0
- rate-limit-1.4.1
- spool-0.1
- status-notifier-item-0.3.0.1
- time-units-1.0.0
- xml-helpers-1.0.0
